name: stratigrapy

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - pip
  - landlab
  - tqdm
  - cmocean
  - pyvista
  - trame
  - trame-vtk
  - trame-vuetify
  - jupyter
  - pip:
    - stratigrapy
