name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build tool
        run: python -m pip install build
      - name: Build sdist
        run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz

  build-wheels:
    name: Build wheels on ${{ matrix.cibw-only }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-13, cibw-only: cp310-macosx_x86_64 }
          - { os: macos-13, cibw-only: cp311-macosx_x86_64 }
          - { os: macos-13, cibw-only: cp312-macosx_x86_64 }
          - { os: macos-13, cibw-only: cp313-macosx_x86_64 }
          - { os: macos-14, cibw-only: cp310-macosx_arm64 }
          - { os: macos-14, cibw-only: cp311-macosx_arm64 }
          - { os: macos-14, cibw-only: cp312-macosx_arm64 }
          - { os: macos-14, cibw-only: cp313-macosx_arm64 }
          - { os: ubuntu-24.04, cibw-only: cp310-manylinux_x86_64 }
          - { os: ubuntu-24.04, cibw-only: cp311-manylinux_x86_64 }
          - { os: ubuntu-24.04, cibw-only: cp312-manylinux_x86_64 }
          - { os: ubuntu-24.04, cibw-only: cp313-manylinux_x86_64 }
          - { os: ubuntu-24.04-arm, cibw-only: cp310-manylinux_aarch64 }
          - { os: ubuntu-24.04-arm, cibw-only: cp311-manylinux_aarch64 }
          - { os: ubuntu-24.04-arm, cibw-only: cp312-manylinux_aarch64 }
          - { os: ubuntu-24.04-arm, cibw-only: cp313-manylinux_aarch64 }
          - { os: windows-2022, cibw-only: cp310-win_amd64 }
          - { os: windows-2022, cibw-only: cp311-win_amd64 }
          - { os: windows-2022, cibw-only: cp312-win_amd64 }
          - { os: windows-2022, cibw-only: cp313-win_amd64 }

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel
      - name: Build wheel
        run: python -m cibuildwheel --only ${{ matrix.cibw-only }}
        env:
          CIBW_ARCHS_MACOS: "x86_64 arm64"
      - uses: actions/upload-artifact@v4
        with:
          name: dist-wheel-${{ matrix.cibw-only }}
          path: wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    needs:
      - build-sdist
      - build-wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
